// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjZOKFT1VDe-pnU7uTZ54EyMTW0EI9pD4',
    appId: '1:983510944871:web:c2b37842cb70430b65d8c2',
    messagingSenderId: '983510944871',
    projectId: 'ecommerce-5594a',
    authDomain: 'ecommerce-5594a.firebaseapp.com',
    storageBucket: 'ecommerce-5594a.firebasestorage.app',
    measurementId: 'G-C7XWZXF2ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZMhqC7b_9qei51oKfV_Yoe0j3BXRV12w',
    appId: '1:983510944871:android:b374b8c27e8e871365d8c2',
    messagingSenderId: '983510944871',
    projectId: 'ecommerce-5594a',
    storageBucket: 'ecommerce-5594a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD71KW5-aznKveJziYR5GPKN1RXN9h_lzI',
    appId: '1:983510944871:ios:bd728e960b13b5b665d8c2',
    messagingSenderId: '983510944871',
    projectId: 'ecommerce-5594a',
    storageBucket: 'ecommerce-5594a.firebasestorage.app',
    iosClientId: '983510944871-p85t5099bcodg0knsl2f45dv31372orq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD71KW5-aznKveJziYR5GPKN1RXN9h_lzI',
    appId: '1:983510944871:ios:bd728e960b13b5b665d8c2',
    messagingSenderId: '983510944871',
    projectId: 'ecommerce-5594a',
    storageBucket: 'ecommerce-5594a.firebasestorage.app',
    iosClientId: '983510944871-p85t5099bcodg0knsl2f45dv31372orq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjZOKFT1VDe-pnU7uTZ54EyMTW0EI9pD4',
    appId: '1:983510944871:web:9e8ff9e4a702145965d8c2',
    messagingSenderId: '983510944871',
    projectId: 'ecommerce-5594a',
    authDomain: 'ecommerce-5594a.firebaseapp.com',
    storageBucket: 'ecommerce-5594a.firebasestorage.app',
    measurementId: 'G-NGJ8VVY3MG',
  );

}