// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMTkUCA6FlS-eZjc6bXGqejI71yOU3DNs',
    appId: '1:624452197062:web:1b6d26667c007700cc15c7',
    messagingSenderId: '624452197062',
    projectId: 'shoepify-6828b',
    authDomain: 'shoepify-6828b.firebaseapp.com',
    storageBucket: 'shoepify-6828b.firebasestorage.app',
    measurementId: 'G-HP4XQPYWPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBML2i6t-SDEiv3Sbaz5Dd8Zgl-vJV-SFo',
    appId: '1:624452197062:android:9246282bc26a5175cc15c7',
    messagingSenderId: '624452197062',
    projectId: 'shoepify-6828b',
    storageBucket: 'shoepify-6828b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnGRQ-YALSnUSyxXKTOVY7zl1mSuGXNFc',
    appId: '1:624452197062:ios:d9af1ef67cb32a21cc15c7',
    messagingSenderId: '624452197062',
    projectId: 'shoepify-6828b',
    storageBucket: 'shoepify-6828b.firebasestorage.app',
    iosClientId: '624452197062-tpmusnvugoua8ocrphtkqg1aflt9cjhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnGRQ-YALSnUSyxXKTOVY7zl1mSuGXNFc',
    appId: '1:624452197062:ios:d9af1ef67cb32a21cc15c7',
    messagingSenderId: '624452197062',
    projectId: 'shoepify-6828b',
    storageBucket: 'shoepify-6828b.firebasestorage.app',
    iosClientId: '624452197062-tpmusnvugoua8ocrphtkqg1aflt9cjhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMTkUCA6FlS-eZjc6bXGqejI71yOU3DNs',
    appId: '1:624452197062:web:176ca0cc43679465cc15c7',
    messagingSenderId: '624452197062',
    projectId: 'shoepify-6828b',
    authDomain: 'shoepify-6828b.firebaseapp.com',
    storageBucket: 'shoepify-6828b.firebasestorage.app',
    measurementId: 'G-EXL5C8XMEJ',
  );
}
